name: "Publish items to MicroCMS"
description: "Publish items to MicroCMS"

runs:
  using: "composite"
  steps:
    # 変更が加えられたファイル名を取得する

    # Qiita

    # 変更が加えられたファイルをMicroCMSにアップロードする
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: Install dependencies
      shell: bash
      run: |
        go run ../../cmd/microcms-publisher/main.go
      working-directory: ${{ github.action_path }}