name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test -cover ./...