name: Publish articles to MicroCMS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "public/**"

permissions:
  contents: write

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Kdaito/microcms-publish/actions/publish@main
        with:
          api-key: ${{ secrets.MICROCMS_API_KEY }}
          service-id: ${{ secrets.MICROCMS_SERVICE_ID }}
          qiita-token: ${{ secrets.QIITA_TOKEN }}
